### ISSUE TITLE
SQLSerializer crashes with multiple aliases

### ISSUE THREAD

**Issue by bigmars86** [knipknap/django-find#2]
When having multiple aliases defined for a specific field (in your searchable attribute in a Searchable class) then django-find inserts the same alias for the columns in the generated query. This is results in an invalid SQL statement.<br>
<br>
The solutions would be either to define the aliases used in the generated statement or add a counter for the generated aliases which have multiple appearances. The last solution should be implemented as a failsave anyway.

**Comment by knipknap** [comment]
Good work! :-)
