### ISSUE TITLE
Can you explain why about mysqlclient installer?

### ISSUE THREAD

**Issue by kwhandy** [knipknap/django-find#4]
`
Collecting mysqlclient
  Using cached mysqlclient-2.0.1.tar.gz (87 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/handy/Files/Projects/web/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/setup.py'"'"'; __file__='"'"'/private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-pip-egg-info-7sd6i3u7
         cwd: /private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/
    Complete output (12 lines):
    /bin/sh: mysql_config: command not found
    /bin/sh: mariadb_config: command not found
    /bin/sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/setup.py", line 15, in <module>
        metadata, options = get_config()
      File "/private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/setup_posix.py", line 65, in get_config
        libs = mysql_config("libs")
      File "/private/var/folders/w9/lzs36g6s6jn_35qlm8ksm1lh0000gn/T/pip-install-reyy38ge/mysqlclient/setup_posix.py", line 31, in mysql_config
        raise OSError("{} not found".format(_mysql_config_path))
    OSError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`

**Comment by knipknap** [comment]
I think you aren't posting in the right place; this looks like a problem with mysqlclient, not with django-find.

**Comment by ali1234** [comment]
This happens when you try to `pip install django-find` on a system that doesn't have mysql installed. It happens because you have a dependency on mysqlclient python package, which can't work without the mysql tools. Django itself does not depend on mysql, having several different database backends, so it is quite likely that people won't have mysql installed.
